// Visual review sheet for the generated icons.
//
// Usage: node tools/favicons-review.mjs
// Output: ../qa/favicons.html — self-contained, so it opens from disk or from
// the dev server at /qa/favicons.html.
//
// Run this after tools/favicons.mjs, and look at the 16 px row before you
// accept a change. Small-size legibility is the only hard problem here: the
// bars must stay separate, with no soft columns between them.
import { chromium } from "playwright";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "src/static");
const QA = join(ROOT, "../qa");

const MIME = { svg: "image/svg+xml", ico: "image/x-icon", png: "image/png" };
const uri = (f) => `data:${MIME[f.split(".").pop()]};base64,`
  + readFileSync(join(SRC, f)).toString("base64");

const tab = (label, file, size) => `
  <figure class="fig">
    <div class="tabstrip"><span class="tab">
      <img src="${uri(file)}" width="${size}" height="${size}" alt="">
      <span>Kancelaria Noriet — Adwokat…</span>
    </span></div>
    <figcaption>${label}</figcaption>
  </figure>`;

const zoom = (label, file, size, factor) => `
  <figure class="fig">
    <img class="px" src="${uri(file)}" width="${size * factor}" height="${size * factor}" alt="">
    <figcaption>${label}</figcaption>
  </figure>`;

const html = `<!-- generated by tools/favicons-review.mjs — do not hand-edit -->
<title>Noriet favicons — review sheet</title>
<style>
  :root { color-scheme: light dark; }
  body { margin: 0; font: 14px/1.5 system-ui, sans-serif; background: #fff; color: #111; }
  h1 { font-size: 20px; margin: 24px 24px 4px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: .06em;
       color: #666; margin: 28px 24px 8px; font-weight: 600; }
  p.note { margin: 0 24px 12px; color: #555; max-width: 60em; }
  .row { display: flex; flex-wrap: wrap; gap: 22px; padding: 12px 24px 4px; align-items: flex-end; }
  .row.dark { background: #202124; }
  .row.dark figcaption { color: #bbb; }
  .row.grey { background: #cfd3d8; }
  .fig { margin: 0; text-align: center; }
  figcaption { font-size: 11px; color: #666; margin-top: 6px; white-space: nowrap; }
  img.px { image-rendering: pixelated; display: block; }
  .tabstrip { background: #dee1e6; padding: 6px 6px 0; border-radius: 8px 8px 0 0; }
  .row.dark .tabstrip { background: #35363a; }
  .tab { display: flex; align-items: center; gap: 7px; background: #fff;
         border-radius: 8px 8px 0 0; padding: 8px 14px; font-size: 12px;
         color: #202124; max-width: 210px; overflow: hidden; white-space: nowrap; }
  .row.dark .tab { background: #202124; color: #e8eaed; }
  /* inline-block so the ring wraps the image, not the caption width */
  .mask { position: relative; display: inline-block; line-height: 0; }
  .mask::after { content: ""; position: absolute; inset: 10%; border: 2px dashed #e0245e;
                 border-radius: 50%; pointer-events: none; }
  .squircle img { border-radius: 22.5%; display: block; }
</style>

<h1>Noriet favicons — review sheet</h1>
<p class="note">Generated from <code>src/static/</code>. Every icon carries the full
five-part mark. The tab icons use a copy snapped to a 16-unit grid, so the bars
land on whole pixels at 16, 32 and 48.</p>

<h2>Browser tab, actual size</h2>
<div class="row">${tab("favicon.ico @16", "favicon.ico", 16)}${tab("favicon.svg @16", "favicon.svg", 16)}${tab("favicon.svg @32 (2x display)", "favicon.svg", 32)}</div>
<div class="row dark">${tab("favicon.ico @16 dark", "favicon.ico", 16)}${tab("favicon.svg @16 dark", "favicon.svg", 16)}${tab("favicon.svg @32 dark", "favicon.svg", 32)}</div>

<h2>Pixel grid</h2>
<p class="note">Zoomed with nearest-neighbour, so you see exactly which pixels the
browser paints. All four bars must stay separate, with hard edges. Only the
diagonal may show soft pixels.</p>
<div class="row">${zoom("16 x8", "favicon.ico", 16, 8)}${zoom("32 x4", "favicon.ico", 32, 4)}${zoom("48 x3", "favicon.ico", 48, 3)}</div>

<h2>App icons</h2>
<div class="row grey">
  <figure class="fig squircle"><img src="${uri("apple-touch-icon.png")}" width="120" height="120" alt=""><figcaption>apple-touch-icon, iOS mask</figcaption></figure>
  <figure class="fig"><img src="${uri("icon-192.png")}" width="120" height="120" alt=""><figcaption>icon-192 (any)</figcaption></figure>
  <figure class="fig"><img src="${uri("icon-512.png")}" width="120" height="120" alt=""><figcaption>icon-512 (any)</figcaption></figure>
</div>

<h2>Maskable safe zone</h2>
<p class="note">The dashed circle is the 80% safe circle of the maskable spec. A
launcher may crop anything outside it. All artwork must stay inside.</p>
<div class="row grey">
  <figure class="fig"><span class="mask"><img src="${uri("icon-maskable-512.png")}" width="150" height="150" alt=""></span><figcaption>icon-maskable-512</figcaption></figure>
  <figure class="fig"><span class="mask"><img src="${uri("icon-maskable-192.png")}" width="150" height="150" alt=""></span><figcaption>icon-maskable-192</figcaption></figure>
  <figure class="fig"><span class="mask"><img src="${uri("icon-512.png")}" width="150" height="150" alt=""></span><figcaption>icon-512 — overflows on purpose, it is not maskable</figcaption></figure>
</div>

<h2>Safari pinned tab</h2>
<div class="row">
  <figure class="fig"><img src="${uri("safari-pinned-tab.svg")}" width="16" height="16" alt=""><figcaption>16, Safari tints it</figcaption></figure>
  <figure class="fig"><img class="px" src="${uri("safari-pinned-tab.svg")}" width="96" height="96" alt=""><figcaption>96</figcaption></figure>
</div>
`;

mkdirSync(QA, { recursive: true });
const out = join(QA, "favicons.html");
writeFileSync(out, html);
console.log(`wrote ${out}`);

const browser = await chromium.launch({ args: ["--no-sandbox"] });
try {
  const page = await browser.newPage({ viewport: { width: 900, height: 1400 }, deviceScaleFactor: 2 });
  await page.setContent(html);
  await page.waitForTimeout(200);
  const png = join(QA, "favicons.png");
  await page.screenshot({ path: png, fullPage: true });
  console.log(`wrote ${png}`);
} finally {
  await browser.close();
}
